version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dashboard_app
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_api
    restart: unless-stopped
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: dashboard_app
      DB_USERNAME: laravel
      DB_PASSWORD: laravelpass
      APP_KEY: base64:changeme
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - app_network
    command: sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nuxt_frontend
    restart: unless-stopped
    environment:
      NUXT_PUBLIC_API_URL: http://localhost:8000/api
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network
    command: sh -c "npm install && npm run dev"

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
